# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/getCut_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 181)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.end = QtWidgets.QLabel(Dialog)
        self.end.setObjectName("end")
        self.gridLayout.addWidget(self.end, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.startPointBox = QtWidgets.QLineEdit(Dialog)
        self.startPointBox.setObjectName("startPointBox")
        self.gridLayout.addWidget(self.startPointBox, 0, 1, 1, 1)
        self.endPointBox = QtWidgets.QLineEdit(Dialog)
        self.endPointBox.setObjectName("endPointBox")
        self.gridLayout.addWidget(self.endPointBox, 1, 1, 1, 1)
        self.deltaKBox = QtWidgets.QLineEdit(Dialog)
        self.deltaKBox.setObjectName("deltaKBox")
        self.gridLayout.addWidget(self.deltaKBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.end.setText(_translate("Dialog", "End (x1,y1)"))
        self.label_2.setText(_translate("Dialog", "Start (x0,y0)"))
        self.label_3.setText(_translate("Dialog", "delta k"))
